# GitHub Actions workflow: Build and Package Windows Executable
# This workflow builds the JavaFX application into a Windows executable installer (.exe)
# using Maven and jpackage.

name: Build and Package Windows Executable

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # 1. Check-out the repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 21. 'temurin' distribution includes jpackage.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build with Maven. This creates the fat/uber JAR.
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. Run jpackage to create a Windows .exe installer
      - name: Package as .exe installer
        run: |
          jpackage --type exe `
            --name "QuoteInvoiceGenerator" `
            --app-version 1.0 `
            --input target/ `
            --main-jar TCStest-1.0-SNAPSHOT.jar `
            --main-class com.example.tcstest.Main `
            --icon src/main/resources/images/logo.png `
            --dest release/ `
            --vendor "YourCompany"
            
      # 5. Upload the generated installer as a build artifact
      - name: Upload executable installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: release/
